# Generated by Django 2.2.8 on 2021-08-12 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodosdepagoPais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', django_countries.fields.CountryField(max_length=2)),
                ('disponible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodsCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('operation_id', models.CharField(max_length=250)),
                ('payment_type', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('payment_flow_type', models.CharField(max_length=255)),
                ('currencies', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequiredFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=50)),
                ('metodos', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsByMerchantRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPayment', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(max_length=255)),
                ('original_amount', models.CharField(max_length=255, null=True)),
                ('merchant_reference_id', models.CharField(max_length=255)),
                ('expiration', models.CharField(max_length=255)),
                ('paid_at', models.CharField(max_length=255)),
                ('textual_codes', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RequiredFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=25)),
                ('message', models.CharField(max_length=255)),
                ('response_code', models.CharField(max_length=50)),
                ('operation_id', models.CharField(max_length=255)),
                ('payment_type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('typetype', models.CharField(max_length=50)),
                ('regex', models.CharField(max_length=50)),
                ('is_required', models.BooleanField()),
                ('minimum_expiration_seconds', models.IntegerField()),
                ('maximum_expiration_seconds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', django_countries.fields.CountryField(max_length=2, null=True)),
                ('tipo_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_usuario', to='rapydcollect.TipoUsuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PerfilU', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('response_code', models.CharField(max_length=255)),
                ('operation_id', models.CharField(max_length=255)),
                ('idPayment', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('is_partial', models.BooleanField(null=True)),
                ('currency_code', models.CharField(max_length=5)),
                ('country_code', django_countries.fields.CountryField(max_length=2)),
                ('statusData', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=50)),
                ('merchant_reference_id', models.CharField(max_length=255)),
                ('customer_token', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=255)),
                ('id_method', models.CharField(max_length=255)),
                ('type_methos', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('metadata_payment', jsonfield.fields.JSONField()),
                ('expiration', models.IntegerField(null=True)),
                ('captured', models.BooleanField(null=True)),
                ('refunded', models.BooleanField(null=True)),
                ('refunded_amount', models.IntegerField(null=True)),
                ('receipt_email', models.CharField(max_length=50)),
                ('redirect_url', models.CharField(max_length=50)),
                ('complete_payment_url', models.CharField(max_length=50)),
                ('receipt_number', models.CharField(max_length=50)),
                ('flow_type_payment', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('statement_descriptor', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(max_length=50)),
                ('created_at', models.IntegerField(null=True)),
                ('metadata', jsonfield.fields.JSONField()),
                ('failure_code', models.CharField(max_length=50)),
                ('failure_message', models.CharField(max_length=255)),
                ('paid', models.BooleanField(null=True)),
                ('paid_at', models.IntegerField(null=True)),
                ('dispute', jsonfield.fields.JSONField()),
                ('refunds', jsonfield.fields.JSONField()),
                ('order', models.CharField(max_length=255)),
                ('outcome', jsonfield.fields.JSONField()),
                ('visual_codes', jsonfield.fields.JSONField()),
                ('textual_codes', jsonfield.fields.JSONField(null=True)),
                ('payCode', models.CharField(max_length=255, null=True)),
                ('instructions', jsonfield.fields.JSONField()),
                ('ewallet_id', models.CharField(max_length=255)),
                ('ewallets', jsonfield.fields.JSONField()),
                ('ewallets_id', models.CharField(max_length=255)),
                ('ewallets_amount', models.IntegerField(null=True)),
                ('ewallets_percent', models.IntegerField(null=True)),
                ('ewallets_refunded_amount', models.IntegerField(null=True)),
                ('payment_method_options', jsonfield.fields.JSONField()),
                ('payment_method_type', models.CharField(max_length=255)),
                ('payment_method_type_category', models.CharField(max_length=100)),
                ('merchant_requested_currency', models.BooleanField(null=True)),
                ('merchant_requested_amount', models.BooleanField(null=True)),
                ('webhook_data', jsonfield.fields.JSONField()),
                ('fechaPago', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetodosdepagoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('disponible_por_tipo_usuario', models.ManyToManyField(to='rapydcollect.TipoUsuario')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapydcollect.MetodosdepagoPais')),
            ],
        ),
        migrations.AddField(
            model_name='metodosdepagopais',
            name='disponible_por_tipo_usuario',
            field=models.ManyToManyField(to='rapydcollect.TipoUsuario'),
        ),
        migrations.AddField(
            model_name='metodosdepagopais',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pais_pago', to='rapydcollect.Paises'),
        ),
        migrations.CreateModel(
            name='DireccionRapyd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=250)),
                ('numexterior', models.CharField(max_length=250)),
                ('numinterior', models.CharField(max_length=250)),
                ('municipio', models.CharField(max_length=250)),
                ('ciudad', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=250)),
                ('codigopostal', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_direccionrapyd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
