from .datosFijosPDF import DatosFijosPDF
from .catalocodigostef import CatalogoCodigosTEF
from .archivoscotia import Archivo
from .cuentaCargo import CuentaCargo
from .scotiatransferencia import ScotiaTransferencia
from .comisionScotia import ComisionesScotia
from .scotiadeposito import ScotiaDeposito
from .scotiaretiro import ScotiaRetiro
from .respuestaScotia import RespuestaScotia
