# Generated by Django 2.2.8 on 2020-05-07 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demograficos', '0001_initial'),
        ('banca', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionBanjico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('short_id', models.CharField(blank=True, max_length=3, null=True)),
                ('long_id', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StpInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_id', models.CharField(max_length=3)),
                ('long_id', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='StpTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stpEstado', models.IntegerField(choices=[(0, 'esperando respuesta'), (1, 'liquidado'), (2, 'devuelto')], default=0)),
                ('statusTrans', models.IntegerField(choices=[(0, 'STP'), (1, 'sendAbono'), (2, 'BanoError'), (3, 'InstitucionError')], default=0)),
                ('institucionOrdenante', models.CharField(blank=True, max_length=50, null=True)),
                ('institucionBeneficiaria', models.CharField(blank=True, max_length=50, null=True)),
                ('stpId', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('banco', models.CharField(blank=True, max_length=50, null=True)),
                ('clabe', models.CharField(blank=True, max_length=18, null=True)),
                ('concepto', models.CharField(blank=True, max_length=128, null=True)),
                ('referencia', models.CharField(blank=True, max_length=18, null=True)),
                ('estado', models.CharField(blank=True, max_length=32, null=True)),
                ('empresa', models.CharField(blank=True, max_length=64, null=True)),
                ('folioOrigen', models.CharField(blank=True, max_length=64, null=True)),
                ('causaDevolucion', models.CharField(blank=True, max_length=64, null=True)),
                ('monto', models.CharField(blank=True, max_length=64, null=True)),
                ('fechaOperacion', models.CharField(blank=True, max_length=64, null=True)),
                ('claveRastreo', models.CharField(blank=True, max_length=64, null=True)),
                ('nombreOrdenante', models.CharField(blank=True, max_length=64, null=True)),
                ('tipoCuentaOrdenante', models.CharField(blank=True, max_length=64, null=True)),
                ('cuentaOrdenante', models.CharField(blank=True, max_length=64, null=True)),
                ('rfcCurpOrdenante', models.CharField(blank=True, max_length=64, null=True)),
                ('nombreBeneficiario', models.CharField(blank=True, max_length=64, null=True)),
                ('tipoCuentaBeneficiario', models.CharField(blank=True, max_length=64, null=True)),
                ('cuentaBeneficiario', models.CharField(blank=True, max_length=64, null=True)),
                ('rfcCurpBeneficiario', models.CharField(blank=True, max_length=64, null=True)),
                ('conceptoPago', models.CharField(blank=True, max_length=64, null=True)),
                ('referenciaNumerica', models.CharField(blank=True, max_length=64, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ubicacion', models.CharField(blank=True, max_length=64, null=True)),
                ('balance', models.CharField(blank=True, max_length=10, null=True)),
                ('verifListaNegra', models.CharField(choices=[('O', 'Ok'), ('P', 'Politicamente Expuesto'), ('N', 'Lista Negra')], default='O', max_length=1)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacto_stp_transaccion', to='demograficos.Contacto')),
                ('institucionBeneficiariaInt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iB_iB', to='spei.InstitutionBanjico')),
                ('institucionOrdenanteInt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iO_iB', to='spei.InstitutionBanjico')),
                ('transaccion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='banca.Transaccion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_stp_transaccion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
