# Generated by Django 2.2.8 on 2020-05-13 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stptransaction',
            name='fechaOperacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
