# Generated by Django 2.2.8 on 2020-05-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stptransaction',
            name='stpMsg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
