# Generated by Django 2.2.8 on 2020-05-15 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0002_stptransaction_stpmsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stptransaction',
            name='institucionBeneficiariaInt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iB_iB', to='spei.InstitutionBanjico'),
        ),
        migrations.AlterField(
            model_name='stptransaction',
            name='institucionOrdenanteInt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iO_iB', to='spei.InstitutionBanjico'),
        ),
        migrations.AlterField(
            model_name='stptransaction',
            name='transaccion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banca.Transaccion'),
        ),
    ]
