# Generated by Django 2.2.8 on 2020-05-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0002_auto_20200513_1646'),
        ('spei', '0003_auto_20200515_0535'),
    ]

    operations = [
    ]
