# Generated by Django 2.2.8 on 2020-05-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0004_merge_20200515_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stptransaction',
            name='clabe',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='stptransaction',
            name='claveRastreo',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='stptransaction',
            name='monto',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='stptransaction',
            name='referencia',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
