# Generated by Django 2.2.8 on 2020-09-03 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generador', '0002_auto_20200903_0256'),
        ('spei', '0005_auto_20200525_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='stptransaction',
            name='archivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivo_intercambio', to='generador.Archivo'),
        ),
    ]
