# Generated by Django 2.2.8 on 2020-09-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0006_stptransaction_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stptransaction',
            name='archivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='generador.Archivo'),
        ),
    ]
