# Generated by Django 2.2.8 on 2020-09-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0007_auto_20200903_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stptransaction',
            name='archivo',
        ),
    ]
