# Generated by Django 2.2.8 on 2021-01-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0008_remove_stptransaction_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminUtils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('util', models.CharField(max_length=30, verbose_name='Utilidades')),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Administrar Utilidades',
            },
        ),
        migrations.AddField(
            model_name='stptransaction',
            name='rechazada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stptransaction',
            name='rechazadaMsj',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stptransaction',
            name='statusTrans',
            field=models.IntegerField(choices=[(0, 'STP'), (1, 'sendAbono'), (2, 'BanoError'), (3, 'InstitucionError'), (4, 'sendabonoEmpresaNoPermitida'), (5, 'sendabonoDesahabilitado'), (6, 'sendabonoErrorCuentaEmpresa')], default=0),
        ),
    ]
