# Generated by Django 2.2.8 on 2021-01-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0008_remove_stptransaction_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPersonaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=164, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=64, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=64, null=True)),
                ('cuenta', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('rfc_curp', models.CharField(blank=True, max_length=20, null=True)),
                ('genero', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha_nacimiento', models.CharField(blank=True, max_length=8, null=True)),
                ('entidad_fededativa', models.CharField(blank=True, max_length=64, null=True)),
                ('actividad_economica', models.CharField(blank=True, max_length=64, null=True)),
                ('calle', models.CharField(blank=True, max_length=64, null=True)),
                ('num_exterior', models.CharField(blank=True, max_length=8, null=True)),
                ('num_interior', models.CharField(blank=True, max_length=8, null=True)),
                ('colonia', models.CharField(blank=True, max_length=64, null=True)),
                ('alcaldia_municipio', models.CharField(blank=True, max_length=64, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=5, null=True)),
                ('pais_nacimiento', models.CharField(blank=True, max_length=32, null=True)),
                ('id_identificacion', models.CharField(blank=True, max_length=32, null=True)),
                ('telefono', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
