# Generated by Django 2.2.8 on 2021-02-04 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0009_auto_20210129_0254'),
        ('spei', '0009_cuentapersonafisica'),
    ]

    operations = [
    ]
