# Generated by Django 2.2.8 on 2022-04-29 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spei', '0010_merge_20210204_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentapersonafisica',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_clabe', to=settings.AUTH_USER_MODEL),
        ),
    ]
