# Generated by Django 2.2.8 on 2022-04-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0011_cuentapersonafisica_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StpNotificacionEstadoDeCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(blank=True, max_length=18)),
                ('empresa', models.CharField(blank=True, max_length=15)),
                ('estado', models.CharField(blank=True, max_length=1)),
                ('observaciones', models.CharField(blank=True, max_length=512)),
            ],
        ),
    ]
