# Generated by Django 2.2.8 on 2022-05-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0013_auto_20220505_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='stptransaction',
            name='tsLiquidacion',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
