# Generated by Django 2.2.8 on 2022-05-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0014_stptransaction_tsliquidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentapersonafisica',
            name='folioCodi',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='cuentapersonafisica',
            name='tipoPago',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
