# Generated by Django 2.2.8 on 2022-05-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0015_auto_20220510_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentapersonafisica',
            name='folioCodi',
        ),
        migrations.RemoveField(
            model_name='cuentapersonafisica',
            name='tipoPago',
        ),
        migrations.AddField(
            model_name='stptransaction',
            name='folioCodi',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='stptransaction',
            name='tipoPago',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
