# Generated by Django 2.2.8 on 2022-05-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0016_auto_20220510_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stptransaction',
            name='fechaOperacion',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
