# Generated by Django 2.2.8 on 2022-06-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0017_auto_20220511_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentapersonafisica',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='cuentapersonafisica',
            name='num_exterior',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='cuentapersonafisica',
            name='num_interior',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='stptransaction',
            name='fechaOperacion',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
