# Generated by Django 2.2.8 on 2022-06-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0018_auto_20220601_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='stptransaction',
            name='reservado',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
