# Generated by Django 2.2.8 on 2022-06-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0019_stptransaction_reservado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stptransaction',
            name='reservado',
            field=models.CharField(default='0', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='stptransaction',
            name='stpEstado',
            field=models.IntegerField(choices=[(0, 'esperando respuesta'), (1, 'liquidado'), (2, 'devuelto'), (3, 'verificado'), (4, 'rechazada')], default=0),
        ),
    ]
