# Generated by Django 2.2.8 on 2022-06-19 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0020_auto_20220615_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stptransaction',
            name='stpEstado',
            field=models.IntegerField(choices=[(0, 'esperando respuesta'), (1, 'exito'), (2, 'devolucion')], default=0),
        ),
    ]
