# Generated by Django 2.2.8 on 2022-07-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0021_auto_20220618_2325'),
        ('spei', '0021_auto_20220620_2020'),
    ]

    operations = [
    ]
