# Generated by Django 3.2.14 on 2022-07-22 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0021_auto_20220618_2325'),
        ('spei', '0021_auto_20220620_2020'),
    ]

    operations = [
    ]
