# Generated by Django 3.2.14 on 2022-07-26 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0023_inguztransaction'),
        ('spei', '0022_merge_0021_auto_20220618_2325_0021_auto_20220620_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacionSTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicial')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha final')),
                ('tipo_orden_conciliacion', models.CharField(choices=[('E', 'Enviadas'), ('R', 'Recibidas')], default='E', max_length=1, verbose_name='Tipo de transacción')),
                ('conciliado', models.BooleanField(default=False, verbose_name='Conciliación realizada')),
                ('hora_de_conciliacion', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de la conciliación')),
            ],
            options={
                'verbose_name': 'Conciliación STP por fecha',
                'verbose_name_plural': 'Conciliación STP por fechas',
            },
        ),
        migrations.AddField(
            model_name='stptransaction',
            name='conciliado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MovimientoConciliacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEF', models.CharField(blank=True, max_length=64, null=True)),
                ('claveRastreo', models.CharField(max_length=64, null=True)),
                ('conceptoPago', models.CharField(blank=True, max_length=64, null=True)),
                ('cuentaBeneficiario', models.CharField(blank=True, max_length=64, null=True)),
                ('cuentaOrdenante', models.CharField(blank=True, max_length=64, null=True)),
                ('empresa', models.CharField(blank=True, max_length=64, null=True)),
                ('estado', models.CharField(blank=True, max_length=32, null=True)),
                ('fechaOperacion', models.DateField()),
                ('institucionContraparte', models.CharField(blank=True, max_length=64, null=True)),
                ('institucionOperante', models.CharField(blank=True, max_length=50, null=True)),
                ('medioEntrega', models.CharField(blank=True, max_length=64, null=True)),
                ('monto', models.CharField(max_length=64, null=True)),
                ('nombreBeneficiario', models.CharField(blank=True, max_length=64, null=True)),
                ('nombreOrdenante', models.CharField(blank=True, max_length=64, null=True)),
                ('nombreCep', models.CharField(blank=True, max_length=100, null=True)),
                ('rfcCep', models.CharField(blank=True, max_length=64, null=True)),
                ('sello', models.CharField(blank=True, max_length=200, null=True)),
                ('rfcCurpBeneficiario', models.CharField(blank=True, max_length=64, null=True)),
                ('referenciaNumerica', models.CharField(blank=True, max_length=200, null=True)),
                ('rfcCurpOrdenante', models.CharField(blank=True, max_length=64, null=True)),
                ('tipoCuentaBeneficiario', models.CharField(blank=True, max_length=64, null=True)),
                ('tipoCuentaOrdenante', models.CharField(blank=True, max_length=64, null=True)),
                ('tipoPago', models.IntegerField(blank=True, null=True)),
                ('tsCaptura', models.CharField(blank=True, max_length=64, null=True)),
                ('tsLiquidacion', models.CharField(blank=True, max_length=64, null=True)),
                ('causaDevolucion', models.CharField(blank=True, max_length=1024, null=True)),
                ('urlCEP', models.CharField(blank=True, max_length=1024, null=True)),
                ('conciliada', models.BooleanField(default=False)),
                ('conciliacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ConciliacionSTP', to='spei.conciliacionstp')),
                ('stpTransaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='StpConciliada', to='spei.stptransaction', verbose_name='Transacción STP conciliada')),
            ],
            options={
                'verbose_name': 'Movimiento Conciliado',
                'verbose_name_plural': 'Movimientos Conciliados',
            },
        ),
    ]
