# Generated by Django 2.2.8 on 2022-07-11 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0022_auto_20220619_2119'),
        ('spei', '0022_merge_20220708_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='stptransaction',
            name='saldoReservado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stpReservado', to='banca.SaldoReservado', verbose_name='Saldo reservado'),
        )
    ]
