# Generated by Django 3.2 on 2023-06-29 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0024_auto_20220926_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentapersonafisica',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
