# Generated by Django 3.2 on 2023-02-21 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0002_auto_20230209_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratod',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomerD',
        ),
        migrations.RemoveField(
            model_name='movimientod',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='id_credito',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='id_entidad',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='user',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='alertas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='comentarios',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='concepto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cuenta',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cuentaclabeB',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cuentaclabeS',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='curp',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='usuario_pld',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='urlspld',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='monto_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.DeleteModel(
            name='ContratoD',
        ),
        migrations.DeleteModel(
            name='MovimientoD',
        ),
    ]
