# Generated by Django 3.2 on 2023-02-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0004_alter_customer_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='alertas',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='mensaje',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='usuario_pld',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
