# Generated by Django 3.2 on 2023-03-06 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0006_auto_20230224_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertasPLD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1056)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(max_length=1056)),
            ],
        ),
    ]
