# Generated by Django 3.2.16 on 2023-02-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bartola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='statics')),
                ('url', models.URLField(blank=True, max_length=300, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=300, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Link e imagen',
                'verbose_name_plural': 'Links e imágenes',
            },
        ),
    ]
