# Generated by Django 3.2.16 on 2023-02-07 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='statics')),
                ('url', models.URLField(blank=True, max_length=300, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=300, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Link e imagen',
                'verbose_name_plural': 'Links e imágenes',
            },
        ),
        migrations.CreateModel(
            name='Respaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'APROBADA'), ('P', 'PENDIENTE'), ('D', 'DECLINADA'), ('V', 'VENCIDA')], default='P', max_length=10, verbose_name='Solicitud')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('contacto_id', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ID del contacto')),
                ('contrato', models.FileField(blank=True, null=True, upload_to='contratos-respaldos')),
                ('activo', models.BooleanField(default=True)),
                ('ordenante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respaldos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('respaldo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respaldados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Respaldos',
            },
        ),
    ]
