# Generated by Django 2.2.8 on 2020-05-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfLegal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=69)),
                ('Pdf', models.FileField(blank=True, null=True, upload_to='docs/pdfLegal')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('validado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Clausulas Legales',
            },
        ),
    ]
