# Generated by Django 2.2.8 on 2022-06-16 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdflegal',
            name='Pdf',
        ),
        migrations.RemoveField(
            model_name='pdflegal',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='pdflegal',
            name='validado',
        ),
        migrations.CreateModel(
            name='PdfLegalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pdf', models.FileField(blank=True, null=True, upload_to='docs/pdfLegal')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('validado', models.BooleanField(default=False)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='legal.PdfLegal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clausulas Legales de Usuario',
            },
        ),
    ]
