# Generated by Django 3.2 on 2023-04-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_alter_pdflegaluser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdflegaluser',
            name='url_pdf',
            field=models.URLField(blank=True, max_length=2056, null=True),
        ),
    ]
