# Generated by Django 2.2.8 on 2020-05-07 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banca', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoCampos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentValidated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EP', 'Empty'), ('IN', 'Invalid'), ('VA', 'Valid')], default='EP', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DepositosRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField()),
                ('fecha', models.DateField()),
                ('importe', models.FloatField()),
                ('Tarjeta', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Depositos Raw',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea1', models.CharField(blank=True, max_length=50, null=True)),
                ('linea2', models.CharField(blank=True, max_length=50, null=True)),
                ('num_int', models.CharField(blank=True, max_length=30, null=True)),
                ('num_ext', models.CharField(blank=True, max_length=30, null=True)),
                ('codPostal', models.CharField(blank=True, max_length=6, null=True)),
                ('colonia', models.CharField(blank=True, max_length=30, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('delegMunicipio', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaCreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('validado', models.BooleanField(blank=True, default=False, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='DocAdjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='demograficos/docs')),
                ('ruta', models.CharField(blank=True, max_length=50, null=True)),
                ('validado', models.BooleanField(blank=True, default=False, null=True)),
                ('orden', models.BooleanField(blank=True, default=True, help_text='1 es frente 0         es reverso', null=True)),
                ('fechaCreado', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocAdjuntoTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EntidadFed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IndiceDisponible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='INE_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=30, null=True)),
                ('curp', models.CharField(blank=True, max_length=20)),
                ('numero_INE', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfoValidator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('limiteCredito', models.IntegerField(default=2800)),
                ('minPorcentaje', models.IntegerField(default=10)),
                ('maxPorcentaje', models.IntegerField(default=15)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'verbose_name': 'Institucion',
                'verbose_name_plural': 'Instituciones',
            },
        ),
        migrations.CreateModel(
            name='PreguntaSeguridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ProspectosRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depositosID', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Prospectos Raw',
            },
        ),
        migrations.CreateModel(
            name='ProveedorTelefonico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=30)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Proveedores telefonicos',
            },
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRespuesta', models.DateTimeField(null=True)),
                ('catalogoCampos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demograficos.CatalogoCampos')),
            ],
        ),
        migrations.CreateModel(
            name='StatusCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='StatusRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='StatusTarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDireccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTelefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Uprofile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('blocked_reason', models.CharField(choices=[('B', 'Su cuenta ha sido bloqueada, por favor contactenos'), ('T', 'Su cuenta ha sido bloqueada por exceso de intentos de inicio de sesión'), ('I', 'Su cuenta ha sido bloqueada por exceso de intentos de inicio de sesión'), ('K', 'OK')], default='K', max_length=1)),
                ('blocked_date', models.DateTimeField(blank=True, null=True)),
                ('login_attempts', models.PositiveSmallIntegerField(default=0)),
                ('login_attempts_inside', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('O', 'Ok'), ('B', 'Bloqueada'), ('C', 'Suscripción cancelada')], default='O', max_length=1)),
                ('apMaterno', models.CharField(blank=True, max_length=30)),
                ('sexo', models.CharField(blank=True, max_length=1)),
                ('curp', models.CharField(blank=True, max_length=20)),
                ('numero_INE', models.CharField(blank=True, max_length=20, null=True)),
                ('verificacion_curp', models.BooleanField(default=False)),
                ('fechaNaciemiento', models.DateField(blank=True, null=True)),
                ('verificacion_email', models.BooleanField(default=False)),
                ('autorizado', models.BooleanField(default=False)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('ineCaptura', models.ImageField(blank=True, null=True, upload_to='docs/ine')),
                ('ineReversoCaptura', models.ImageField(blank=True, null=True, upload_to='docs/ineReverso')),
                ('comprobanteDomCaptura', models.ImageField(blank=True, null=True, upload_to='docs/comprobanteDom')),
                ('statusNip', models.CharField(choices=[('U', 'UNSET'), ('A', 'ACTIVE'), ('B', 'BLOCKED')], default='U', max_length=1)),
                ('aceptaKitLegal', models.DateTimeField(blank=True, null=True)),
                ('saldo_dde', models.FloatField(blank=True, default=0, null=True)),
                ('saldo_cuenta', models.FloatField(blank=True, default=0, null=True)),
                ('cuentaClabe', models.CharField(blank=True, max_length=18)),
                ('ocupacion', models.CharField(blank=True, max_length=30)),
                ('nacionalidad', models.CharField(blank=True, max_length=30)),
                ('ciudad_nacimiento', models.CharField(blank=True, max_length=30)),
                ('rfc', models.CharField(blank=True, max_length=20, null=True)),
                ('comprobantedom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobante_dom', to='demograficos.DocAdjunto')),
                ('indiceDisponible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demograficos.IndiceDisponible')),
                ('ine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ine', to='demograficos.DocAdjunto')),
                ('ineReverso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ine_reverso', to='demograficos.DocAdjunto')),
                ('statusCuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_cuenta', to='demograficos.StatusCuenta')),
                ('statusRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_registro', to='demograficos.StatusRegistro')),
            ],
            options={
                'verbose_name_plural': 'Perfil del usuario',
            },
        ),
        migrations.CreateModel(
            name='UserNotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=500)),
                ('fechaCreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('logger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WhoDidIt', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_notas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('mac', models.CharField(blank=True, max_length=100, null=True)),
                ('gps', models.CharField(blank=True, max_length=500, null=True)),
                ('active', models.BooleanField(default=True)),
                ('unique_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('dev_model', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_device', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBeneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('parentesco', models.CharField(blank=True, max_length=30)),
                ('apellido_materno', models.CharField(blank=True, max_length=30)),
                ('apellido_paterno', models.CharField(blank=True, max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo_electronico', models.EmailField(max_length=80, null=True)),
                ('rfc', models.CharField(blank=True, max_length=30, null=True)),
                ('curp', models.CharField(blank=True, max_length=30, null=True)),
                ('participacion', models.FloatField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True, null=True)),
                ('direccion_L1', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_L2', models.CharField(blank=True, max_length=20, null=True)),
                ('dir_num_int', models.CharField(blank=True, max_length=20, null=True)),
                ('dir_num_ext', models.CharField(blank=True, max_length=20, null=True)),
                ('dir_colonia', models.CharField(blank=True, max_length=30, null=True)),
                ('dir_CP', models.CharField(blank=True, max_length=6, null=True)),
                ('dir_estado', models.CharField(blank=True, max_length=20, null=True)),
                ('dir_municipio', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Beneficiario_direccion', to='demograficos.Direccion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Beneficiario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('extension', models.CharField(blank=True, max_length=6, null=True)),
                ('fechaCreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('prefijo', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('validado', models.BooleanField(default=False)),
                ('proveedorTelefonico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demograficos.ProveedorTelefonico')),
                ('tipoTelefono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demograficos.TipoTelefono')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_telefono', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjetaDebitoNum', models.CharField(blank=True, max_length=20, null=True)),
                ('tarjetaDebitoPin', models.CharField(blank=True, max_length=6, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demograficos.Institucion')),
                ('statusTarjeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demograficos.StatusTarjeta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tarjeta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoyClienteDe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demograficos.Institucion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cliente de',
            },
        ),
        migrations.CreateModel(
            name='SolicitudIncompleta',
            fields=[
                ('fechaSolicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='solicitud_incompleta', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('catalogo_campos', models.ManyToManyField(through='demograficos.Respuestas', to='demograficos.CatalogoCampos')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaSeguridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_secreta', models.CharField(blank=True, max_length=100)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demograficos.PreguntaSeguridad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='respuestas',
            name='solicitudIncompleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demograficos.SolicitudIncompleta'),
        ),
        migrations.CreateModel(
            name='Prospectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=80)),
                ('tarjeta', models.CharField(max_length=16)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('vecesDeContacto', models.IntegerField(default=0)),
                ('candidato', models.BooleanField(default=False)),
                ('sumaTotal', models.FloatField(default=0)),
                ('promedio', models.FloatField(default=0)),
                ('limiteCreditoReal', models.FloatField(default=0)),
                ('limiteCreditoRedondeado', models.FloatField(default=0)),
                ('maximo', models.FloatField(default=0)),
                ('minimo', models.FloatField(default=0)),
                ('desvEst', models.FloatField(blank=True, default=0, null=True)),
                ('porcentaje', models.FloatField(default=10)),
                ('depositosPromedio', models.FloatField(default=0)),
                ('fechaCreacion', models.DateTimeField(auto_now=True)),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demograficos.Institucion')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Uprospecto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prospecto',
                'verbose_name_plural': 'Prospectos',
            },
        ),
        migrations.CreateModel(
            name='ProfileComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=32)),
                ('rn_screen', models.CharField(max_length=32)),
                ('verified_status', models.ManyToManyField(through='demograficos.ComponentValidated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='preguntaseguridad',
            name='respuesta_secreta',
            field=models.ManyToManyField(through='demograficos.RespuestaSeguridad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=10)),
                ('ssid', models.CharField(blank=True, max_length=40)),
                ('fechaCreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('telefono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PVTelefono', to='demograficos.Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='NipTemporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('nip_temp', models.CharField(blank=True, max_length=6, null=True)),
                ('attempts', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_nipTemp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='institucion',
            name='user',
            field=models.ManyToManyField(through='demograficos.SoyClienteDe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='INE_Reg_Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('approved', models.BooleanField(blank=True, default=0, null=True)),
                ('back', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_Attempt', to='demograficos.INE_Info')),
                ('front', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='front_Attempt', to='demograficos.INE_Info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AttemptsSet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaLinea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineaCredito', models.FloatField(blank=True, null=True)),
                ('lineaDisponible', models.FloatField(blank=True, null=True)),
                ('fechaApertura', models.DateTimeField(blank=True, null=True)),
                ('fechaCierre', models.DateTimeField(blank=True, null=True)),
                ('fechaCongelada', models.DateTimeField(blank=True, null=True)),
                ('fechaUltTrans', models.DateTimeField(blank=True, null=True)),
                ('saldoCuenta', models.FloatField(blank=True, null=True)),
                ('fechaLinea', models.DateTimeField(default=django.utils.timezone.now)),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_HistoriaLinea', to='banca.Productos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_HistoriaLinea', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='docadjunto',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_documento', to='demograficos.DocAdjuntoTipo'),
        ),
        migrations.AddField(
            model_name='docadjunto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_documento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='direccion',
            name='entidadFed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demograficos.EntidadFed'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='tipo_direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demograficos.TipoDireccion'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_direccion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Depositos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField(default=1)),
                ('fecha', models.DateField()),
                ('importe', models.FloatField()),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demograficos.Prospectos')),
            ],
            options={
                'verbose_name': 'Deposito',
                'verbose_name_plural': 'Depositos',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('nombreCompleto', models.CharField(default='', max_length=200, null=True)),
                ('ap_paterno', models.CharField(default='', max_length=30)),
                ('ap_materno', models.CharField(default='', max_length=30)),
                ('banco', models.CharField(max_length=69)),
                ('clabe', models.CharField(max_length=18)),
                ('activo', models.BooleanField(default=True)),
                ('verificacion', models.CharField(choices=[('O', 'Ok'), ('P', 'Politicamente Expuesto'), ('N', 'Lista Negra')], default='O', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contactos_Usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lista de Contactos',
            },
        ),
        migrations.CreateModel(
            name='ComportamientoMensual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('retiroMensualTotal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('depositoMensualTotal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('numretiros', models.IntegerField(blank=True, default=0, null=True)),
                ('numdepositos', models.IntegerField(blank=True, default=0, null=True)),
                ('depositoMensualPromedio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('retiroMensualPromedio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('alarmaretiro', models.BooleanField(default=False)),
                ('alarmadeposito', models.BooleanField(default=False)),
                ('montoInusualMensual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CAMIM_comportamiento', to='banca.CAMIM')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comportamientom', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComportamientoDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excesotransaccion', models.BooleanField(default=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('numtrans', models.FloatField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comportamientod', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='componentvalidated',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demograficos.ProfileComponent'),
        ),
        migrations.AddField(
            model_name='componentvalidated',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Columnas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('equivalencia', models.CharField(max_length=80)),
                ('nombreSalida', models.CharField(max_length=80)),
                ('default', models.CharField(max_length=80)),
                ('formato', models.CharField(max_length=80)),
                ('comentario', models.CharField(max_length=80)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demograficos.Institucion')),
            ],
            options={
                'verbose_name': 'Columna',
                'verbose_name_plural': 'Columnas',
            },
        ),
        migrations.CreateModel(
            name='BinBanco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.CharField(max_length=6)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demograficos.Institucion')),
            ],
        ),
    ]
