# Generated by Django 2.2.8 on 2020-05-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0002_auto_20200509_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbeneficiario',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userbeneficiario',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
