# Generated by Django 2.2.8 on 2020-05-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0003_auto_20200510_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbeneficiario',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userbeneficiario',
            name='verif_curp',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
