# Generated by Django 2.2.8 on 2020-05-12 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demograficos', '0005_administradore_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('bloqueo', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('ultacceso', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('cancelacion', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('reactivacion', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('cambionip', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('cambiopssword', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('cambiodispositivo', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('cambioidtelcliente', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('registrocodi', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ufecha', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
