# Generated by Django 2.2.8 on 2020-05-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0006_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='bloqueo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='cambiodispositivo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='cambioidtelcliente',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='cambionip',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='cambiopssword',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='reactivacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='registrocodi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='ultacceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
