# Generated by Django 2.2.8 on 2020-05-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0007_auto_20200512_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirmacion_dde',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fechaCreacion_dde',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_dde',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nip',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
