# Generated by Django 2.2.8 on 2020-05-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0007_auto_20200512_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntaseguridad',
            name='tipo_nip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='respuestaseguridad',
            name='tipo_nip',
            field=models.BooleanField(default=False),
        ),
    ]
