# Generated by Django 2.2.8 on 2020-05-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0008_auto_20200513_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fecha',
            old_name='cambiodispositivo',
            new_name='cambio_de_contraseña',
        ),
        migrations.RenameField(
            model_name='fecha',
            old_name='cambioidtelcliente',
            new_name='cambio_de_dispositivo',
        ),
        migrations.RenameField(
            model_name='fecha',
            old_name='cambionip',
            new_name='cambio_de_nip',
        ),
        migrations.RenameField(
            model_name='fecha',
            old_name='cambiopssword',
            new_name='cambio_id_cliente_telefonico',
        ),
        migrations.RenameField(
            model_name='fecha',
            old_name='registrocodi',
            new_name='creacion_dde',
        ),
        migrations.RenameField(
            model_name='fecha',
            old_name='ultacceso',
            new_name='registro_codi',
        ),
        migrations.AddField(
            model_name='fecha',
            name='ultimo_acceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
