# Generated by Django 2.2.8 on 2020-05-16 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("banca", '0007_cami'),
        ('demograficos', '0008_auto_20200513_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comportamientomensual',
            name='montoInusualMensual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CAMIM_comportamiento', to='banca.CAMI'),
        ),
    ]
