# Generated by Django 2.2.8 on 2020-05-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0010_auto_20200516_1400'),
        ('demograficos', '0009_auto_20200517_2143'),
    ]

    operations = [
    ]
