# Generated by Django 2.2.8 on 2020-05-19 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0011_merge_20200518_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administradore',
        ),
    ]
