# Generated by Django 2.2.8 on 2020-05-21 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0012_delete_administradore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepositosRaw',
        ),
        migrations.DeleteModel(
            name='ProspectosRaw',
        ),
    ]
