# Generated by Django 2.2.8 on 2020-05-28 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0008_auto_20200514_1601'),
        ('demograficos', '0013_auto_20200520_2327'),
    ]

    operations = [
    ]
