# Generated by Django 2.2.8 on 2020-05-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0014_merge_20200528_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecomponent',
            name='indice',
            field=models.IntegerField(default=0),
        ),
    ]
