# Generated by Django 2.2.8 on 2020-06-17 11:43

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0015_profilecomponent_indice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedortelefonico',
            name='country',
            field=django_countries.fields.CountryField(default='MX', max_length=2),
        ),
    ]
