# Generated by Django 2.2.8 on 2020-06-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0016_auto_20200617_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentvalidated',
            name='motivo_invalido',
            field=models.CharField(default='EP', max_length=2),
        ),
    ]
