# Generated by Django 2.2.8 on 2020-07-31 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0017_componentvalidated_motivo_invalido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ine_info',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='ine_info',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='ine_info',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='ine_info',
            name='numero_INE',
        ),
        migrations.AddField(
            model_name='ine_info',
            name='a_materno',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='ine_info',
            name='a_paterno',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AddField(
            model_name='ine_info',
            name='año',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ine_info',
            name='calle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ine_info',
            name='clave_elector',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='ine_info',
            name='colonia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ine_info',
            name='delegacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ine_info',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ine_info',
            name='emision',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ine_info',
            name='estado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ine_info',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ine_info',
            name='folio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ine_info',
            name='isFront',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ine_info',
            name='localidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ine_info',
            name='municipio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ine_info',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ine_info',
            name='seccion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ine_info',
            name='sexo',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='ine_info',
            name='vigencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ine_info',
            name='curp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
