# Generated by Django 2.2.8 on 2020-07-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0017_componentvalidated_motivo_invalido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentvalidated',
            name='motivo_invalido',
            field=models.CharField(default='EP', max_length=255),
        ),
    ]
