# Generated by Django 2.2.8 on 2020-07-10 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0018_auto_20200709_1725'),
        ('demograficos', '0018_restorepassword'),
    ]

    operations = [
    ]
