# Generated by Django 2.2.8 on 2020-07-31 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0018_auto_20200731_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ine_info',
            old_name='año',
            new_name='anio',
        ),
    ]
