# Generated by Django 2.2.8 on 2020-08-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0019_auto_20200731_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='ine_info',
            name='fecha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
