# Generated by Django 2.2.8 on 2020-07-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0019_merge_20200709_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminUtils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('util', models.CharField(max_length=30, verbose_name='Utilidades')),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Administrar Utilidades',
            },
        ),
    ]
