# Generated by Django 2.2.8 on 2020-08-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0020_ine_info_fecha'),
        ('demograficos', '0021_geodevice_geolocation'),
    ]

    operations = [
    ]
