# Generated by Django 2.2.8 on 2020-07-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0021_geodevice_geolocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidatedToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
            ],
        ),
    ]
