# Generated by Django 2.2.8 on 2020-08-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0022_merge_20200803_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fechaNaciemiento',
            new_name='fecha_nacimiento',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='apMaterno',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='curp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sexo',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
