# Generated by Django 2.2.8 on 2020-08-12 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0023_auto_20200804_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='confirmacion_dde',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fechaCreacion_dde',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id_dde',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='saldo_dde',
        ),
    ]
