# Generated by Django 2.2.8 on 2020-08-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0023_auto_20200804_1507'),
        ('demograficos', '0022_invalidatedtoken'),
    ]

    operations = [
    ]
