# Generated by Django 2.2.8 on 2020-08-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0023_auto_20200804_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='calle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='linea1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='linea2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
