# Generated by Django 2.2.8 on 2020-08-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0024_merge_20200812_1245'),
        ('demograficos', '0024_merge_20200816_2238'),
    ]

    operations = [
    ]
