# Generated by Django 2.2.8 on 2020-08-22 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0024_auto_20200812_1758'),
        ('demograficos', '0025_merge_20200817_1228'),
    ]

    operations = [
    ]
