# Generated by Django 2.2.8 on 2020-08-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0026_merge_20200821_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirmacion_dde',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fechaCreacion_dde',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_dde',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saldo_dde',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
