# Generated by Django 2.2.8 on 2020-08-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0024_auto_20200810_2217'),
        ('demograficos', '0027_auto_20200824_1235'),
    ]

    operations = [
    ]
