# Generated by Django 2.2.8 on 2020-08-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0028_merge_20200824_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='validacion_direccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='validacion_perfil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='validacion_telefono',
            field=models.BooleanField(default=False),
        ),
    ]
