# Generated by Django 2.2.8 on 2020-09-08 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0029_auto_20200831_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntaseguridad',
            options={'verbose_name_plural': 'Preguntas de seguridad'},
        ),
    ]
