# Generated by Django 2.2.8 on 2020-09-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0030_auto_20200908_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbeneficiario',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=80, null=True),
        ),
    ]
