# Generated by Django 2.2.8 on 2020-09-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0030_auto_20200908_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbeneficiario',
            name='activo',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
