# Generated by Django 2.2.8 on 2020-09-22 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0031_auto_20200917_1309'),
        ('demograficos', '0031_auto_20200922_1512'),
    ]

    operations = [
    ]
