# Generated by Django 2.2.8 on 2020-09-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0032_merge_20200922_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbeneficiario',
            name='activo',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
