# Generated by Django 2.2.8 on 2020-09-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0033_auto_20200923_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbeneficiario',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userbeneficiario',
            name='dir_colonia',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='userbeneficiario',
            name='dir_estado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userbeneficiario',
            name='dir_municipio',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='userbeneficiario',
            name='direccion_L1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userbeneficiario',
            name='direccion_L2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
