# Generated by Django 2.2.8 on 2021-02-03 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0018_entidades'),
        ('demograficos', '0035_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='usuarioEntidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userProfile_entidades', to='banca.Entidades'),
        ),
    ]
