# Generated by Django 2.2.8 on 2021-02-04 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demograficos', '0035_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodevice',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilecomponent',
            name='default_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='componentvalidated',
            name='motivo_invalido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='componentvalidated',
            name='status',
            field=models.CharField(choices=[('EP', 'Empty'), ('IN', 'Invalid'), ('VA', 'Valid')], max_length=2),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_device', to='demograficos.GeoDevice'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to='demograficos.GeoLocation'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=None, max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='udevices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
