# Generated by Django 2.2.8 on 2021-02-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0036_auto_20210204_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentvalidated',
            name='status',
            field=models.CharField(blank=True, choices=[('EP', 'Empty'), ('IN', 'Invalid'), ('VA', 'Valid')], max_length=2, null=True),
        ),
    ]
