# Generated by Django 2.2.8 on 2021-02-08 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0037_auto_20210204_1832'),
        ('demograficos', '0024_auto_20200805_1953'),
    ]

    operations = [
    ]
