# Generated by Django 2.2.8 on 2021-02-09 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0038_merge_20210208_1715'),
        ('demograficos', '0036_userprofile_usuarioentidad'),
    ]

    operations = [
    ]
