# Generated by Django 2.2.8 on 2021-02-11 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0039_merge_20210209_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='usuarioEntidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userProfile_entidades', to='banca.Entidades'),
        ),
    ]
