# Generated by Django 2.2.8 on 2021-02-17 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demograficos', '0040_auto_20210210_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidadfed',
            name='clave',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ocr_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DocExtraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validacion', models.FloatField(null=True)),
                ('diccionario', models.CharField(max_length=5000, null=True)),
                ('detalles', models.CharField(max_length=5000, null=True)),
                ('errores', models.CharField(max_length=5000, null=True)),
                ('documento', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demograficos.DocAdjunto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
