# Generated by Django 2.2.8 on 2021-05-12 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0019_auto_20210512_1150'),
        ('demograficos', '0042_remove_docextraction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='usuarioEntidad',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='usuarioCodigoConfianza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userProfile_codigo_de_confianza', to='banca.CodigoConfianza'),
        ),
    ]
