# Generated by Django 2.2.8 on 2022-04-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0043_auto_20210512_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='validacion_cuenta_en_STP',
            field=models.BooleanField(default=False),
        ),
    ]
