# Generated by Django 2.2.8 on 2022-05-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0044_userprofile_validacion_cuenta_en_stp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cuenta_clabe_bloqueada',
            field=models.BooleanField(default=False),
        ),
    ]
