# Generated by Django 2.2.8 on 2022-07-14 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0047_auto_20220701_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='userbeneficiario',
            name='parentesco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parentesco_Beneficiario', to='demograficos.Parentesco'),
        ),
    ]
