# Generated by Django 3.2 on 2022-10-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0048_auto_20220713_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='comprobantedom',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ine',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ineReverso',
        ),
    ]
