# Generated by Django 3.2 on 2022-10-08 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0049_auto_20220926_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='comprobantedom',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ine',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ineReverso',
        ),
    ]
