# Generated by Django 3.2 on 2022-10-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0050_auto_20221007_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
