# Generated by Django 3.2 on 2022-11-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0052_auto_20221115_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='frecuencia',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
