# Generated by Django 3.2 on 2022-11-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0053_contacto_frecuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='alias_inguz',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alias',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='avatar_img',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
