# Generated by Django 3.2 on 2022-11-23 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demograficos', '0054_auto_20221116_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enrolamiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_telefono', to=settings.AUTH_USER_MODEL),
        ),
    ]
