# Generated by Django 3.2 on 2022-11-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0055_auto_20221122_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='es_inguz',
            field=models.BooleanField(default=True),
        ),
    ]
