# Generated by Django 3.2 on 2022-12-20 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0058_contacto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
