# Generated by Django 3.2 on 2022-12-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0058_contacto_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pais_origen_otro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pais de nacimiento'),
        ),
    ]
