# Generated by Django 3.2.16 on 2022-12-30 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0058_contacto_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='login',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
