# Generated by Django 3.2 on 2023-01-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0059_auto_20221230_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avatar',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Mujer'), ('H', 'Hombre'), ('O', 'Otro')], max_length=15, null=True),
        ),
    ]
