# Generated by Django 3.2 on 2023-01-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0059_auto_20221230_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avatar',
            name='genero',
            field=models.CharField(blank=True, choices=[('1', 'Mujer'), ('2', 'Hombre'), ('3', 'Otro')], max_length=15, null=True),
        ),
    ]
