# Generated by Django 3.2 on 2023-01-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0061_auto_20230109_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
