# Generated by Django 3.2.16 on 2023-01-17 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demograficos', '0064_userprofile_nivel_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiltransaccionaldeclarado',
            name='status_perfil',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfiltransaccionaldeclarado',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
