# Generated by Django 3.2.16 on 2023-01-18 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0065_auto_20230117_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demograficos.avatar'),
        ),
    ]
