# Generated by Django 3.2.16 on 2023-01-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0066_auto_20230118_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='avatar_min_img',
        ),
        migrations.AddField(
            model_name='avatar',
            name='avatar_min',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Avatar miniatura'),
        ),
    ]
