# Generated by Django 3.2 on 2023-01-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0067_auto_20230118_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pais_origen_otro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pais de nacimiento'),
        ),
    ]
