# Generated by Django 3.2 on 2023-01-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0068_userprofile_pais_origen_otro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='colonia',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='delegMunicipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
