# Generated by Django 3.2 on 2023-01-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0068_userprofile_pais_origen_otro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docadjunto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
