# Generated by Django 3.2.16 on 2023-02-07 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0070_respaldo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Respaldo',
        ),
    ]
