# Generated by Django 3.2 on 2023-03-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0072_auto_20230209_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docadjunto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
