# Generated by Django 3.2 on 2023-04-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0075_docadjunto_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='numero_transaccion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
