# Generated by Django 3.2 on 2023-04-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0075_docadjunto_imagen_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ocr_ok',
            new_name='ocr_ine_validado',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ocr_comprobante_validado',
            field=models.BooleanField(default=False),
        ),
    ]
