# Generated by Django 3.2 on 2023-04-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0076_auto_20230410_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ciudad_nacimiento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
