# Generated by Django 3.2 on 2023-05-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0078_passwordhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasInvalido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substring_invalida', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
