# Generated by Django 3.2 on 2023-05-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0079_aliasinvalido'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contador_servicio_cliente',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
