# Generated by Django 3.2 on 2023-05-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0080_userprofile_contador_servicio_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='docadjunto',
            name='validacion_frontal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ocr_ine_back_validado',
            field=models.BooleanField(default=False),
        ),
    ]
