# Generated by Django 3.2 on 2023-05-10 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demograficos', '0081_userprofile_pep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_p', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido_m', models.CharField(blank=True, max_length=30, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=100, null=True)),
                ('curp', models.CharField(blank=True, max_length=20, null=True)),
                ('entidad_nacimiento', models.CharField(blank=True, max_length=560, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=50, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_proveedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
