# Generated by Django 3.2 on 2023-05-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0082_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fuente_ingresos_alter',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
