# Generated by Django 3.2 on 2023-05-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0083_userprofile_fuente_ingresos_alter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
