# Generated by Django 3.2 on 2023-05-26 16:27

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('demograficos', '0084_alter_proveedor_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancelacion',
            fields=[
            ],
            options={
                'verbose_name': 'Cuentas Canceladas',
                'verbose_name_plural': 'Cuentas Canceladas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
