# Generated by Django 3.2 on 2023-05-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0086_versionapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='docadjunto',
            name='validado_operador',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
