# Generated by Django 3.2 on 2023-05-31 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0086_versionapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='docadjunto',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docadjunto',
            name='validado_operador',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
