# Generated by Django 3.2 on 2023-05-31 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0087_auto_20230530_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoRechazoDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=1028, null=True)),
                ('codigo', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='perfiltransaccionaldeclarado',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
