# Generated by Django 3.2 on 2023-05-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0088_auto_20230531_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivorechazodoc',
            name='tipo',
            field=models.CharField(choices=[('I', 'INE'), ('C', 'Comprobante')], max_length=16, null=True),
        ),
    ]
