# Generated by Django 3.2 on 2023-05-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0089_motivorechazodoc_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blocked_reason',
            field=models.CharField(choices=[('B', 'Su cuenta ha sido bloqueada, por favor contactenos'), ('T', 'Su cuenta ha sido bloqueada por exceso de intentos de inicio de sesión'), ('I', 'Su cuenta ha sido bloqueada por exceso de intentos de inicio de sesión'), ('K', 'OK'), ('BE', 'Su cuenta fue bloqueada por el flujo de emergencia'), ('BV', 'su cuenta fue bloqueada voluntariamente')], default='K', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('O', 'Ok'), ('B', 'Bloqueada'), ('C', 'Suscripción cancelada'), ('BE', 'Bloqueada de Emergencia'), ('BV', 'Bloqueo Voluntario')], default='O', max_length=2),
        ),
    ]
