# Generated by Django 3.2 on 2023-06-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0091_auto_20230601_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docadjunto',
            name='ruta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
