# Generated by Django 3.2 on 2022-12-19 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CactusDBLogger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslog',
            name='create_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de creación'),
        ),
    ]
