# Generated by Django 3.2 on 2022-10-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('code', models.TextField(blank=True, max_length=500, null=True)),
                ('security', models.TextField(blank=True, max_length=500, null=True)),
                ('json', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Codigo de Cobro',
                'verbose_name_plural': 'Codigos de Cobro',
            },
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc', models.IntegerField(default=0)),
                ('msg', models.CharField(blank=True, max_length=60, null=True)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.TextField(blank=True, max_length=1000, null=True)),
                ('security', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
            },
        ),
    ]
