# Generated by Django 3.2 on 2022-10-20 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0002_codigocobro_reembolso'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del cliente')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Teléfono')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)], verbose_name='Monto del cobro')),
                ('cashout_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)], verbose_name='Monto de retiro')),
                ('code', models.CharField(max_length=50, verbose_name='code QR')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('reference', models.CharField(blank=True, max_length=200, null=True, verbose_name='Referencia')),
                ('response', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Realizar un pago',
                'verbose_name_plural': 'Realizar pagos',
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.CharField(max_length=50, verbose_name='QR ID')),
                ('qr_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción del QR')),
                ('qr_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)], verbose_name='Monto del QR')),
                ('qr_currency', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mondeda de cambio del QR')),
                ('qr_reference_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia numérica del QR')),
                ('cashout_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)], verbose_name='Monto de retiro')),
                ('cashout_currency', models.CharField(blank=True, max_length=50, null=True, verbose_name='Moneda de cambio del retiro')),
                ('merchant_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de comercio')),
                ('merchant_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion de comercio')),
                ('merchant_image', models.CharField(blank=True, max_length=50, null=True, verbose_name='Imagen de comercio')),
                ('merchant_type', models.IntegerField(blank=True, null=True, verbose_name='Tipo de comercio')),
                ('category_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de categoría')),
                ('category_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de Categoría')),
                ('response', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Información de cobro',
                'verbose_name_plural': 'Información de cobros',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID del pago')),
                ('payment_reference', models.CharField(blank=True, max_length=200, null=True, verbose_name='Referencia del pago')),
                ('response', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Información de pago',
                'verbose_name_plural': 'Información de pagos',
            },
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=17, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=17, verbose_name='Longitud')),
                ('radius', models.PositiveIntegerField(blank=True, null=True, verbose_name='radio')),
                ('response', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Información de ubicación de tienda',
                'verbose_name_plural': 'Información de ubicación de tiendas',
            },
        ),
    ]
