# Generated by Django 2.2.8 on 2022-06-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scotiabank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='contenido_archivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
