# Generated by Django 2.2.8 on 2022-06-20 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0022_auto_20220619_2119'),
        ('scotiabank', '0002_archivo_contenido_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='scotiaretiro',
            name='reservado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scotiaRetiroReservado', to='banca.SaldoReservado', verbose_name='Saldo reservado'),
        ),
        migrations.AlterField(
            model_name='scotiaretiro',
            name='statusTrans',
            field=models.IntegerField(choices=[(0, 'Por procesar'), (1, 'Archivo generado'), (2, 'Transacción enviada'), (4, 'Transacción recibida con éxito'), (5, 'Transacción realizada'), (6, 'Error al generar archivo'), (7, 'Error al enviar archivo'), (8, 'Transacción fallida'), (9, 'Devolución')], default=0),
        ),
    ]
