# Generated by Django 2.2.8 on 2022-06-22 01:05

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scotiabank', '0002_archivo_contenido_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosRetiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_vigencia', models.DateField()),
                ('creacion', models.DateTimeField()),
                ('no_empresa', models.PositiveIntegerField(default='17244')),
                ('url_archivo', models.CharField(blank=True, max_length=200, null=True)),
                ('retiro_pdf', models.FileField(blank=True, null=True, storage='/media', upload_to='')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('transaccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scotiabank.ScotiaRetiro')),
            ],
        ),
    ]
