# Generated by Django 2.2.8 on 2022-06-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scotiabank', '0003_datosretiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosretiro',
            name='instrucciones',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
