# Generated by Django 2.2.8 on 2022-07-04 23:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scotiabank', '0004_datosretiro_instrucciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFijosPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transaccion', models.CharField(blank=True, choices=[('Retiro', 'Retiro Scotiabank'), ('Deposito', 'Depósito Scotiabank')], default='Retiro', max_length=50, null=True, unique=True, verbose_name='Tipo de transacción')),
                ('nombre_empresa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del banco')),
                ('numero_empresa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de empresa/convenio:')),
                ('instrucciones', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Datos fijos en comprobante',
                'verbose_name_plural': 'Datos fijos en comprobantes',
            },
        ),
        migrations.AddField(
            model_name='scotiadeposito',
            name='comprobante_pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='scotiadeposito',
            name='numero_empresa',
            field=models.CharField(blank=True, default='4572', max_length=50, null=True, verbose_name='Número de empresa/convenio:'),
        ),
        migrations.AddField(
            model_name='scotiadeposito',
            name='url_comprobante',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='scotiaretiro',
            name='comprobante_pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='scotiaretiro',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True, verbose_name='vigencia de la transacción'),
        ),
        migrations.AddField(
            model_name='scotiaretiro',
            name='numero_empresa',
            field=models.CharField(blank=True, default='17244', max_length=50, null=True, verbose_name='Número de empresa/convenio:'),
        ),
        migrations.AddField(
            model_name='scotiaretiro',
            name='url_comprobante',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='respuestascotia',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respuestascotia',
            name='nombre_archivo',
            field=models.CharField(blank=True, max_length=56, null=True, validators=[django.core.validators.MinLengthValidator(52)], verbose_name='Nombre del archivo'),
        ),
        migrations.AlterField(
            model_name='respuestascotia',
            name='tipo',
            field=models.CharField(blank=True, choices=[('000', 'Por definir'), ('FN2', 'Confirmación de recibido'), ('FN3', 'Resumen movimientos día anterior'), ('FN4', 'Resumen de rechazo día anterior'), ('FN5', 'Confirmación movimiento realizado'), ('H83', 'Resumen de cobranza con recibo')], default='000', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='scotiadeposito',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True, verbose_name='vigencia de la transacción'),
        ),
        migrations.AlterField(
            model_name='scotiadeposito',
            name='importe_documento',
            field=models.DecimalField(decimal_places=2, max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importe total'),
        ),
        migrations.DeleteModel(
            name='DatosRetiro',
        ),
    ]
