# Generated by Django 2.2.8 on 2022-07-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scotiabank', '0005_auto_20220704_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogocodigostef',
            name='descripcion',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='catalogocodigostef',
            name='etiqueta',
            field=models.CharField(choices=[('00-19', 'ERROR DE CICS'), ('20-50', 'ERROR EN VALIDACION'), ('51-60', 'ERROR EN PAGO VENTANILLA'), ('61-  ', 'ERROR EN ARCHIVOS DEFINITIVOS')], max_length=64),
        ),
    ]
