# Generated by Django 2.2.8 on 2022-07-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scotiabank', '0006_auto_20220704_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestascotia',
            name='url_respuesta',
            field=models.URLField(blank=True, max_length=2056, null=True),
        ),
    ]
