# Generated by Django 2.2.8 on 2022-07-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scotiabank', '0007_respuestascotia_url_respuesta'),
        ('scotiabank', '0003_auto_20220619_2119'),
    ]

    operations = [
    ]
