# Generated by Django 2.2.8 on 2022-07-14 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scotiabank', '0009_auto_20220711_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='enviado',
        ),
        migrations.RemoveField(
            model_name='scotiaretiro',
            name='archivo_respuesta_FN5',
        ),
        migrations.AddField(
            model_name='archivo',
            name='errorMsg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mensaje de error'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='respuesta_FN5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FN5_respuesta', to='scotiabank.RespuestaScotia', verbose_name='Respuesta FN5'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Archivo generado'), (1, 'Archivo confirmado por Scotiabank'), (2, 'Archivo rechazado por Scotiabank')], default=0, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='scotiadeposito',
            name='archivo_respuesta_H93',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='H83_deposito', to='scotiabank.RespuestaScotia', verbose_name='Archivo de respuesta'),
        ),
        migrations.AddField(
            model_name='scotiaretiro',
            name='fecha_confirmacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de confirmación FN3'),
        ),
        migrations.AddField(
            model_name='scotiaretiro',
            name='rechazoMsg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mensaje de rechazo'),
        ),
        migrations.AlterField(
            model_name='respuestascotia',
            name='tipo',
            field=models.CharField(blank=True, choices=[('000', 'Por definir'), ('FN2', 'Confirmación de movimiento generado'), ('FN3', 'Resumen movimientos día anterior'), ('FN4', 'Resumen de rechazo día anterior'), ('FN5', 'Respuesta de recibido'), ('H83', 'Resumen de cobranza con recibo (DEF 1'), ('H93', 'Resumen de cobranza con recibo (DEF 2)'), ('###', 'Inválido (no definido)')], default='000', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='scotiaretiro',
            name='archivo_resumen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumen_retiro', to='scotiabank.RespuestaScotia', verbose_name='Archivo FN3 de resumen'),
        ),
        migrations.AlterField(
            model_name='scotiaretiro',
            name='statusTrans',
            field=models.IntegerField(choices=[(0, 'Por procesar'), (1, 'Archivo generado'), (2, 'Transacción recibida por Scotiabank'), (4, 'Transacción confirmada por Scotiabank'), (5, 'Transacción exitosa (retiro realizado)'), (6, 'Error al generar archivo'), (7, 'Error en el archivo enviado'), (8, 'Devolución por transacción no procesada'), (9, 'Devolución por dinero no retirado')], default=0),
        ),
    ]
