# Generated by Django 2.2.8 on 2022-07-15 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scotiabank', '0010_auto_20220714_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
