# Generated by Django 2.2.8 on 2022-07-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scotiabank', '0011_auto_20220715_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scotiaretiro',
            name='conceptoPago',
            field=models.CharField(blank=True, default='Retiro', max_length=50, null=True),
        ),
    ]
