# Generated by Django 3.2 on 2023-02-24 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0032_alter_transaccion_monto'),
        ('scotiabank', '0012_auto_20220716_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scotiaretiro',
            name='transaccion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scotiaRetiro', to='banca.transaccion'),
        ),
    ]
