# Generated by Django 2.2.8 on 2021-03-24 01:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demograficos', '0042_remove_docextraction_user'),
        ('banca', '0018_entidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaSaldo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=32, null=True)),
                ('nombre', models.CharField(blank=True, max_length=64, null=True)),
                ('clabe', models.CharField(blank=True, max_length=20, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=16, null=True)),
            ],
            options={
                'verbose_name_plural': 'Saldo en cuentas',
            },
        ),
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldoinicial', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('debe', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('saldofinal', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('nombre', models.CharField(max_length=55)),
                ('codigo', models.CharField(max_length=30)),
                ('naturaleza', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTransConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Transacción',
            },
        ),
        migrations.CreateModel(
            name='TransaccionCorteTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TransaccionCorte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaTrans', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.FloatField()),
                ('comision', models.FloatField()),
                ('comisionIVA', models.FloatField()),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demograficos.Institucion')),
            ],
        ),
        migrations.CreateModel(
            name='SubcuentaSTPIVA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldoinicial', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('debe', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('saldofinal', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('resumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scstpiva_resumen', to='contabilidad.Resumen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubcuentaIVA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldoinicial', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('debe', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('saldofinal', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('resumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sciva_resumen', to='contabilidad.Resumen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SCDTFTPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldoinicial', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('debe', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('saldofinal', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('resumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SCDTFTPE_resumen', to='contabilidad.Resumen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IVAnoCobrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldoinicial', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('debe', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('saldofinal', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('resumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ivanoco_resumen', to='contabilidad.Resumen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IVAcobrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldoinicial', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('debe', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('saldofinal', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('resumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ivaco_resumen', to='contabilidad.Resumen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IVAacreditableNoPagado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldoinicial', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('debe', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('saldofinal', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('resumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ivacrednop_resumen', to='contabilidad.Resumen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FondosPagoElectronico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldoinicial', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('debe', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('saldofinal', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('resumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpe_resumen', to='contabilidad.Resumen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ejecuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_contable', models.CharField(blank=True, max_length=32, null=True)),
                ('orden', models.FloatField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=16, null=True)),
                ('tipo_trans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.TipoTransConta')),
            ],
            options={
                'verbose_name_plural': 'Orden de ejecución',
            },
        ),
        migrations.CreateModel(
            name='CuentaTerceros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldoinicial', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('debe', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('saldofinal', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('resumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cterceros_resumen', to='contabilidad.Resumen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CuentaSTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldoinicial', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('debe', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('saldofinal', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('resumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cstp_resumen', to='contabilidad.Resumen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CuentaPropia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldoinicial', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('debe', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('saldofinal', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('resumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cp_resumen', to='contabilidad.Resumen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComisionesporPagarSobreOperacionesVigentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldoinicial', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('debe', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('saldofinal', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('resumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copsov_resumen', to='contabilidad.Resumen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComisionesPagadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldoinicial', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('debe', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('saldofinal', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('resumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compa_resumen', to='contabilidad.Resumen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComisionesCobradas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldoinicial', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('debe', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('saldofinal', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('resumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocob_resumen', to='contabilidad.Resumen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cobranza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjetaDebitoNum', models.CharField(blank=True, max_length=20, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('comision', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('comisionIVA', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('statusCobranza', models.CharField(choices=[('PC', 'Por Cobrar'), ('CE', 'Procezada'), ('C', 'Cobrado')], default='PC', max_length=2)),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion_transaccionapago', to='banca.Transaccion')),
            ],
        ),
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('codigo_contable', models.CharField(blank=True, max_length=32, null=True)),
                ('nombre', models.CharField(blank=True, max_length=64, null=True)),
                ('saldo_inicial', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=16, null=True)),
                ('regla_cargo', models.CharField(blank=True, max_length=128, null=True)),
                ('regla_abono', models.CharField(blank=True, max_length=128, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=16, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('ejecuta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contabilidad.Ejecuta')),
                ('tipo_trans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.TipoTransConta')),
            ],
            options={
                'verbose_name_plural': '1. Reglas',
            },
        ),
        migrations.CreateModel(
            name='Dinero',
            fields=[
                ('codigo_contable', models.CharField(blank=True, max_length=32, null=True)),
                ('nombre', models.CharField(blank=True, max_length=64, null=True)),
                ('saldo_inicial', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=16, null=True)),
                ('cargo', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=16, null=True)),
                ('abono', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=16, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=16, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('ejecuta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contabilidad.Ejecuta')),
                ('tipo_trans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.TipoTransConta')),
            ],
            options={
                'verbose_name_plural': '3. Dinero',
            },
        ),
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('codigo_contable', models.CharField(blank=True, max_length=32, null=True)),
                ('nombre', models.CharField(blank=True, max_length=64, null=True)),
                ('saldo_inicial', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=16, null=True)),
                ('cargo', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=16, null=True)),
                ('abono', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=16, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=16, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('ejecuta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contabilidad.Ejecuta')),
                ('tipo_trans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.TipoTransConta')),
            ],
            options={
                'verbose_name_plural': '2. Anotaciones',
            },
        ),
    ]
