# Generated by Django 2.2.8 on 2021-03-30 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipotransconta',
            options={'verbose_name_plural': 'Cuentas'},
        ),
    ]
