# Generated by Django 2.2.8 on 2021-05-12 11:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0018_entidades'),
        ('contabilidad', '0002_auto_20210330_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContableCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=32, null=True)),
                ('orden', models.FloatField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=64, null=True)),
                ('regla_cargo', models.CharField(blank=True, max_length=128, null=True)),
                ('regla_abono', models.CharField(blank=True, max_length=128, null=True)),
                ('cargo_actual', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name='cargo')),
                ('abono_actual', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name='abono')),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True)),
            ],
            options={
                'verbose_name_plural': 'Balanza General',
            },
        ),
        migrations.CreateModel(
            name='CuentaTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regla_cargo', models.CharField(blank=True, max_length=128, null=True)),
                ('regla_abono', models.CharField(blank=True, max_length=128, null=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regla', to='contabilidad.ContableCuenta')),
            ],
        ),
        migrations.CreateModel(
            name='TipoContableCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=64)),
                ('activo', models.BooleanField(default=True)),
                ('cuentas', models.ManyToManyField(related_name='tipos', through='contabilidad.CuentaTipo', to='contabilidad.ContableCuenta')),
            ],
        ),
        migrations.AddField(
            model_name='cuentatipo',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regla', to='contabilidad.TipoContableCuenta'),
        ),
        migrations.CreateModel(
            name='ContableMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suma', models.BooleanField(default=True)),
                ('saldo_inicial', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True)),
                ('cargo', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True)),
                ('abono', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='contabilidad.ContableCuenta')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='contabilidad.TipoContableCuenta')),
                ('transaccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='banca.Transaccion')),
            ],
            options={
                'verbose_name_plural': 'Movimientos',
            },
        ),
        migrations.CreateModel(
            name='ContableCuentaDepositoEfectivoSBProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': '(Depósito Efectivo SB)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contabilidad.contablecuenta',),
        ),
        migrations.CreateModel(
            name='ContableCuentaDepositoEfectivoSCProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': '(Depósito Efectivo SC)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contabilidad.contablecuenta',),
        ),
        migrations.CreateModel(
            name='ContableCuentaRetiroEfectivoSCProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': '(Retiro Efectivo SC)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contabilidad.contablecuenta',),
        ),
        migrations.CreateModel(
            name='ContableCuentaTransferenciaEnviadaProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': '(Transferencia Enviada)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contabilidad.contablecuenta',),
        ),
        migrations.CreateModel(
            name='ContableCuentaTransferenciaRecibidaProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': '(Transferencia Recibida)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contabilidad.contablecuenta',),
        ),
    ]
