# Generated by Django 2.2.8 on 2021-07-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_auto_20210512_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContableCuentaBGProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': '(BALANZA GENERAL)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contabilidad.contablecuenta',),
        ),
        migrations.CreateModel(
            name='ContableCuentaRetiroEfectivoCODIProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': '(CODI)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contabilidad.contablecuenta',),
        ),
        migrations.CreateModel(
            name='ContableCuentaRetiroEfectivoDDEINGUZProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': '(DDE INGUZ)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contabilidad.contablecuenta',),
        ),
        migrations.CreateModel(
            name='ContableCuentaRetiroEfectivoDDEInvercratosProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': '(DDE Invercratos)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contabilidad.contablecuenta',),
        ),
        migrations.CreateModel(
            name='ContableCuentaRetiroEfectivoSBProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': '(Retiro Efectivo SB)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contabilidad.contablecuenta',),
        ),
        migrations.AddField(
            model_name='contablecuenta',
            name='sobrenombre',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
