# Generated by Django 2.2.8 on 2022-04-26 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_auto_20210702_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinero',
            name='ejecuta',
        ),
        migrations.RemoveField(
            model_name='dinero',
            name='tipo_trans',
        ),
        migrations.RemoveField(
            model_name='ejecuta',
            name='tipo_trans',
        ),
        migrations.RemoveField(
            model_name='regla',
            name='ejecuta',
        ),
        migrations.RemoveField(
            model_name='regla',
            name='tipo_trans',
        ),
        migrations.RemoveField(
            model_name='contablecuenta',
            name='abono_actual',
        ),
        migrations.RemoveField(
            model_name='contablecuenta',
            name='cargo_actual',
        ),
        migrations.RemoveField(
            model_name='contablecuenta',
            name='regla_abono',
        ),
        migrations.RemoveField(
            model_name='contablecuenta',
            name='regla_cargo',
        ),
        migrations.RemoveField(
            model_name='contablecuenta',
            name='saldo',
        ),
        migrations.RemoveField(
            model_name='contablemovimiento',
            name='suma',
        ),
        migrations.AddField(
            model_name='contablecuenta',
            name='cuenta_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_hija', to='contabilidad.ContableCuenta'),
        ),
        migrations.AddField(
            model_name='contablecuenta',
            name='es_cuenta_totales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contablecuenta',
            name='orden_admin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Anotacion',
        ),
        migrations.DeleteModel(
            name='Dinero',
        ),
        migrations.DeleteModel(
            name='Ejecuta',
        ),
        migrations.DeleteModel(
            name='Regla',
        ),
        migrations.DeleteModel(
            name='TipoTransConta',
        ),
    ]
