# Generated by Django 2.2.8 on 2022-06-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_auto_20220426_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='contablecuenta',
            name='long_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
