# Generated by Django 3.2 on 2022-06-30 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_contablecuenta_long_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContableCuentaEnviadoInguzInguzProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': '(INGUZ INGUZ Enviada)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contabilidad.contablecuenta',),
        ),
    ]
