# Generated by Django 3.2 on 2022-06-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_contablecuentaenviadoinguzinguzproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContableCuentaRecibidaInguzInguzProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': '(INGUZ INGUZ Recibida)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contabilidad.contablecuenta',),
        ),
    ]
