# Generated by Django 3.2 on 2023-05-08 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecargasArcus',
            fields=[
                ('id_recarga', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('biller_type', models.CharField(blank=True, max_length=256, null=True)),
                ('bill_type', models.CharField(blank=True, max_length=256, null=True)),
                ('country', models.CharField(blank=True, max_length=256, null=True)),
                ('currency', models.CharField(blank=True, max_length=256, null=True)),
                ('requires_name_on_account', models.BooleanField(blank=True, null=True)),
                ('hours_to_fulfill', models.IntegerField(blank=True, null=True)),
                ('account_number_digits', models.CharField(blank=True, max_length=256, null=True)),
                ('mask', models.CharField(blank=True, max_length=256, null=True)),
                ('can_check_balance', models.BooleanField(blank=True, null=True)),
                ('supports_partial_payments', models.BooleanField(blank=True, null=True)),
                ('has_xdata', models.BooleanField(blank=True, null=True)),
                ('available_topup_amounts', models.JSONField(blank=True, null=True)),
                ('topup_commission', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Recargas Arcus',
            },
        ),
        migrations.CreateModel(
            name='ServicesArcus',
            fields=[
                ('id_bill', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('biller_type', models.CharField(blank=True, max_length=256, null=True)),
                ('bill_type', models.CharField(blank=True, max_length=256, null=True)),
                ('country', models.CharField(blank=True, max_length=256, null=True)),
                ('currency', models.CharField(blank=True, max_length=256, null=True)),
                ('requires_name_on_account', models.BooleanField(blank=True, null=True)),
                ('hours_to_fulfill', models.IntegerField(blank=True, null=True)),
                ('account_number_digits', models.CharField(blank=True, max_length=256, null=True)),
                ('mask', models.CharField(blank=True, max_length=256, null=True)),
                ('can_check_balance', models.BooleanField(blank=True, null=True)),
                ('supports_partial_payments', models.BooleanField(blank=True, null=True)),
                ('has_xdata', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Servicios Arcus',
            },
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.IntegerField()),
                ('account_number', models.CharField(max_length=100)),
                ('monto', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bills',
            },
        ),
    ]
