# Generated by Django 3.2 on 2023-05-12 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0036_alter_comisionestp_rangotransacciones'),
        ('arcus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiempoAire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaccion', models.IntegerField(blank=True, null=True)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('moneda', models.CharField(blank=True, max_length=20, null=True)),
                ('monto_usd', models.FloatField(blank=True, null=True)),
                ('comision', models.FloatField(blank=True, null=True)),
                ('total_usd', models.FloatField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, max_length=2056, null=True)),
                ('id_externo', models.CharField(blank=True, max_length=2056, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=2056, null=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('transaccion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaccion_recarga', to='banca.transaccion')),
            ],
        ),
    ]
