# Generated by Django 3.2 on 2023-05-15 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcus', '0002_tiempoaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiempoaire',
            options={'verbose_name_plural': 'Tiempo aire'},
        ),
    ]
