# Generated by Django 3.2 on 2023-05-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcus', '0003_alter_tiempoaire_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesarcus',
            old_name='can_check_balance',
            new_name='allows_reversal',
        ),
        migrations.RenameField(
            model_name='servicesarcus',
            old_name='has_xdata',
            new_name='autopay',
        ),
        migrations.RenameField(
            model_name='servicesarcus',
            old_name='account_number_digits',
            new_name='customer_fee_type',
        ),
        migrations.RenameField(
            model_name='servicesarcus',
            old_name='id_bill',
            new_name='sku_id',
        ),
        migrations.RenameField(
            model_name='servicesarcus',
            old_name='requires_name_on_account',
            new_name='tracking',
        ),
        migrations.RemoveField(
            model_name='servicesarcus',
            name='bill_type',
        ),
        migrations.RemoveField(
            model_name='servicesarcus',
            name='mask',
        ),
        migrations.AddField(
            model_name='servicesarcus',
            name='bill_types',
            field=models.JSONField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='servicesarcus',
            name='customer_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicesarcus',
            name='logo_url',
            field=models.URLField(blank=True, max_length=4096, null=True),
        ),
    ]
