# Generated by Django 3.2 on 2023-05-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcus', '0003_alter_tiempoaire_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recargasarcus',
            old_name='account_number_digits',
            new_name='carrier',
        ),
        migrations.RenameField(
            model_name='recargasarcus',
            old_name='topup_commission',
            new_name='customer_fee',
        ),
        migrations.RenameField(
            model_name='recargasarcus',
            old_name='available_topup_amounts',
            new_name='topup_amounts',
        ),
        migrations.RenameField(
            model_name='servicesarcus',
            old_name='can_check_balance',
            new_name='allows_reversal',
        ),
        migrations.RenameField(
            model_name='servicesarcus',
            old_name='has_xdata',
            new_name='autopay',
        ),
        migrations.RenameField(
            model_name='servicesarcus',
            old_name='account_number_digits',
            new_name='customer_fee_type',
        ),
        migrations.RenameField(
            model_name='servicesarcus',
            old_name='bill_type',
            new_name='sku_id',
        ),
        migrations.RenameField(
            model_name='servicesarcus',
            old_name='requires_name_on_account',
            new_name='tracking',
        ),
        migrations.RemoveField(
            model_name='recargasarcus',
            name='can_check_balance',
        ),
        migrations.RemoveField(
            model_name='recargasarcus',
            name='has_xdata',
        ),
        migrations.RemoveField(
            model_name='recargasarcus',
            name='hours_to_fulfill',
        ),
        migrations.RemoveField(
            model_name='recargasarcus',
            name='id_recarga',
        ),
        migrations.RemoveField(
            model_name='recargasarcus',
            name='requires_name_on_account',
        ),
        migrations.RemoveField(
            model_name='recargasarcus',
            name='supports_partial_payments',
        ),
        migrations.RemoveField(
            model_name='servicesarcus',
            name='id_bill',
        ),
        migrations.RemoveField(
            model_name='servicesarcus',
            name='mask',
        ),
        migrations.AddField(
            model_name='recargasarcus',
            name='customer_fee_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='recargasarcus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recargasarcus',
            name='logo_url',
            field=models.URLField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='recargasarcus',
            name='reference_lenght',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='recargasarcus',
            name='sku_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='servicesarcus',
            name='bill_types',
            field=models.JSONField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='servicesarcus',
            name='customer_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicesarcus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesarcus',
            name='logo_url',
            field=models.URLField(blank=True, max_length=4096, null=True),
        ),
    ]
