# Generated by Django 3.2 on 2023-05-16 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0036_alter_comisionestp_rangotransacciones'),
        ('arcus', '0004_auto_20230515_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosArcus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaccion', models.CharField(blank=True, max_length=2056, null=True)),
                ('tipo', models.CharField(blank=True, max_length=256, null=True)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('moneda', models.CharField(blank=True, max_length=20, null=True)),
                ('identificador', models.CharField(blank=True, max_length=256, null=True)),
                ('comision', models.FloatField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, max_length=2056, null=True)),
                ('id_externo', models.CharField(blank=True, max_length=2056, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=2056, null=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('transaccion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaccion_recarga', to='banca.transaccion')),
            ],
            options={
                'verbose_name_plural': 'Pagos arcus',
            },
        ),
        migrations.DeleteModel(
            name='TiempoAire',
        ),
    ]
