# Generated by Django 3.2 on 2023-05-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcus', '0004_auto_20230515_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiempoaire',
            name='monto_usd',
        ),
        migrations.RemoveField(
            model_name='tiempoaire',
            name='total_usd',
        ),
        migrations.AddField(
            model_name='tiempoaire',
            name='identificador',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tiempoaire',
            name='id_transaccion',
            field=models.CharField(blank=True, max_length=2056, null=True),
        ),
    ]
