# Generated by Django 3.2 on 2022-08-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renapo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renapo',
            name='renapo_ap_mat',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Apellido materno en RENAPO'),
        ),
        migrations.AddField(
            model_name='renapo',
            name='renapo_ap_pat',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Apellido paterno en RENAPO'),
        ),
        migrations.AddField(
            model_name='renapo',
            name='renapo_nacimiento',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Fecha de nacimiento en RENAPO'),
        ),
        migrations.AddField(
            model_name='renapo',
            name='renapo_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre en Renapo'),
        ),
        migrations.AddField(
            model_name='renapo',
            name='renapo_resp',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Respuesta de RENAPO'),
        ),
        migrations.AlterField(
            model_name='renapo',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
