# Generated by Django 3.2 on 2022-08-05 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('renapo', '0002_auto_20220804_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='renapo',
            name='msjError',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mensaje de validación'),
        ),
        migrations.AlterField(
            model_name='renapo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Renapo', to=settings.AUTH_USER_MODEL),
        ),
    ]
