# Generated by Django 2.2.8 on 2020-08-12 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('dde', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DineroDeEmergencia',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ddeinfo', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('id_DDE', models.IntegerField(blank=True, null=True)),
                ('fechaCreacion_DDE', models.DateTimeField(blank=True, null=True)),
                ('confirmacion_DDE', models.BooleanField(default=False)),
                ('aceptaKitLegal_DDE', models.DateTimeField(blank=True, null=True)),
                ('saldo_DDE', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
