# Generated by Django 2.2.8 on 2020-09-18 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dde', '0002_dinerodeemergencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagofondeador',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='producto_fondeador',
            name='producto',
        ),
    ]
