# Generated by Django 2.2.8 on 2020-09-08 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dde', '0002_dinerodeemergencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionDDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transaccion_dde', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
