# Generated by Django 2.2.8 on 2020-09-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dde', '0003_transacciondde'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciondde',
            name='fechaTrans',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
