# Generated by Django 2.2.8 on 2020-09-26 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dde', '0004_transacciondde_fechatrans'),
        ('dde', '0003_auto_20200918_1846'),
    ]

    operations = [
    ]
