# Generated by Django 2.2.8 on 2020-09-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='txt',
            field=models.FileField(blank=True, null=True, upload_to='docs/archivo'),
        ),
    ]
