# Generated by Django 2.2.8 on 2020-09-08 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spei', '0008_remove_stptransaction_archivo'),
        ('generador', '0002_auto_20200903_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='generador.Archivo')),
                ('transaccion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spei.StpTransaction')),
            ],
        ),
    ]
