# Generated by Django 2.2.8 on 2020-09-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generador', '0003_movimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivo',
            old_name='txt',
            new_name='Txt',
        ),
    ]
