# Generated by Django 2.2.8 on 2020-09-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generador', '0004_auto_20200908_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivo',
            old_name='Txt',
            new_name='txt',
        ),
    ]
