# Generated by Django 2.2.8 on 2020-09-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador', '0005_auto_20200908_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='secuencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
