# Generated by Django 2.2.8 on 2020-09-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador', '0006_archivo_secuencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(blank=True, max_length=11, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
