# Generated by Django 2.2.8 on 2020-05-07 20:25

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminUtils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('util', models.CharField(max_length=30, verbose_name='Utilidades')),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Administrar Utilidades',
            },
        ),
        migrations.CreateModel(
            name='CAMID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('monto', models.FloatField()),
                ('unidad', models.CharField(blank=True, max_length=10, null=True)),
                ('pesos', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CAMIM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('monto', models.FloatField()),
                ('unidad', models.CharField(blank=True, max_length=10, null=True)),
                ('pesos', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CarProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('numDiasCobro', models.IntegerField(verbose_name='Dias para Cobro')),
                ('diasVencimiento', models.IntegerField(verbose_name='Dias Para Vencer')),
                ('diasIncobrable', models.IntegerField(verbose_name='Dias Para Incobrable')),
                ('porcentajeComision', models.DecimalField(decimal_places=4, default=0.12, max_digits=30, verbose_name='% Comision')),
                ('porcentajeIVA', models.DecimalField(decimal_places=4, default=0.16, max_digits=30, verbose_name='% Iva de Comision')),
                ('activo', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Creacion')),
            ],
            options={
                'verbose_name_plural': 'Caracteristicas de Productos',
            },
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('descripcion', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ComisioneSTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stp', models.FloatField()),
                ('ivaSTP', models.FloatField()),
                ('cliente', models.FloatField()),
                ('ivaCliente', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ErroresTransaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('mensaje', models.CharField(max_length=128)),
                ('codigo_ext', models.CharField(max_length=4)),
                ('mensaje_ext', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='LogExportadoTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaExportacion', models.DateTimeField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=120, null=True)),
                ('fechaConfirmado', models.DateTimeField(blank=True, null=True)),
                ('fechaCobranza', models.DateTimeField(blank=True, null=True)),
                ('fechaConfirmadoCobranza', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Logs de Transacciones',
            },
        ),
        migrations.CreateModel(
            name='MediosDisponibles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaisesDisponibles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paises', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='StatusTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Estatus de las Transacciones',
            },
        ),
        migrations.CreateModel(
            name='TipoAnual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('numDias', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Tipos Anuales',
            },
        ),
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaValor', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechaAplicacion', models.DateTimeField(blank=True, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Transacciones',
            },
        ),
        migrations.CreateModel(
            name='TransaccionCancelada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaTrans', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('errorCode', models.CharField(blank=True, max_length=10)),
                ('noAutorizacion', models.CharField(blank=True, max_length=50)),
                ('errorDesc', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Transacciones Canceladas',
            },
        ),
        migrations.CreateModel(
            name='TransaccionExterna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaTrans', models.DateTimeField(default=django.utils.timezone.now)),
                ('errorCode', models.IntegerField(blank=True, null=True)),
                ('noAutorizacion', models.CharField(max_length=120)),
                ('quien', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Transacciones Externas',
            },
        ),
        migrations.CreateModel(
            name='TransPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagoTotal', models.DecimalField(blank=True, decimal_places=4, max_digits=30)),
                ('pagoMonto', models.DecimalField(blank=True, decimal_places=4, max_digits=30)),
                ('pagoComision', models.DecimalField(blank=True, decimal_places=4, max_digits=30)),
                ('pagoComisionIVA', models.DecimalField(blank=True, decimal_places=4, max_digits=30)),
                ('lineaDisponible', models.DecimalField(blank=True, decimal_places=4, max_digits=30)),
                ('pagadoMonto', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=30)),
                ('pagadoComision', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=30)),
                ('pagadoComisionIVA', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=30)),
                ('fechaPago', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Transacciones de Pago',
            },
        ),
        migrations.CreateModel(
            name='TransPago_AuthDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(blank=True, decimal_places=4, max_digits=30)),
                ('fechaAplicacion', models.DateTimeField(null=True)),
                ('noAuth', models.CharField(blank=True, max_length=50, null=True)),
                ('statusPago', models.CharField(blank=True, max_length=10, null=True)),
                ('statusCliente', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransPago_AuthHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArchivo', models.CharField(blank=True, max_length=50, null=True)),
                ('depositoRef', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaArchivo', models.DateTimeField(null=True)),
                ('fechaOperacion', models.DateTimeField(null=True)),
                ('fechaAutorizado', models.DateTimeField(null=True)),
                ('montoTotalPagos', models.DecimalField(blank=True, decimal_places=4, max_digits=30)),
                ('numRegistros', models.DecimalField(blank=True, decimal_places=4, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='UploadBNXOutSetSVA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='BNMX_OUTSETSVA'), upload_to='')),
                ('fechaUpload', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadTefOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='BNMX_OUTSETSVA'), upload_to='')),
                ('fechaUpload', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidacionTransaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificacion_db', models.BooleanField(default=False)),
                ('verificacion_https', models.BooleanField(default=False)),
                ('verificacion_intoto', models.BooleanField(default=False)),
                ('transaccion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaccion_ValidacionTransaccion', to='banca.Transaccion')),
            ],
            options={
                'verbose_name_plural': 'Validacion de las transacciones',
            },
        ),
        migrations.CreateModel(
            name='ValidacionSesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epochExp', models.CharField(blank=True, max_length=120, null=True)),
                ('epoxhOrigIat', models.CharField(blank=True, max_length=120, null=True)),
                ('user', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('transaccion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaccion_ValidacionSesion', to='banca.Transaccion')),
            ],
            options={
                'verbose_name_plural': 'Validacion de las sesiones',
            },
        ),
        migrations.CreateModel(
            name='ValidacionRegulatoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarma', models.BooleanField(default=False)),
                ('idCAMID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validacionR_CAMID', to='banca.CAMID')),
                ('transaccion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaccion_validacioR', to='banca.Transaccion')),
            ],
        ),
        migrations.CreateModel(
            name='TransPagoExterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaTrans', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('errorCode', models.CharField(blank=True, max_length=10)),
                ('noAutorizacion', models.CharField(blank=True, max_length=120)),
                ('transpago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transPago_transaccionExterna', to='banca.TransPago')),
            ],
            options={
                'verbose_name_plural': 'Transacciones de Pago Externas',
            },
        ),
    ]
