# Generated by Django 2.2.8 on 2020-05-07 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demograficos', '0001_initial'),
        ('banca', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transpago_authhead',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demograficos.Institucion'),
        ),
        migrations.AddField(
            model_name='transpago_authhead',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TransPago_AuthHead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transpago_authdet',
            name='transPago_AuthHead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banca.TransPago_AuthHead'),
        ),
        migrations.AddField(
            model_name='transpago_authdet',
            name='transaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banca.Transaccion'),
        ),
        migrations.AddField(
            model_name='transpago',
            name='statusTrans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_transPago', to='banca.StatusTrans'),
        ),
        migrations.AddField(
            model_name='transpago',
            name='transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion_transPago', to='banca.Transaccion'),
        ),
        migrations.AddField(
            model_name='transaccionexterna',
            name='transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion_transaccionExterna', to='banca.Transaccion'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='errorRes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_transaccion', to='banca.ErroresTransaccion'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='statusTrans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_transaccion', to='banca.StatusTrans'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='tipoTrans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_transaccion', to='banca.TipoTransaccion'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transaccion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productos',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demograficos.Institucion'),
        ),
        migrations.AddField(
            model_name='productos',
            name='paises_disponibles',
            field=models.ManyToManyField(to='banca.PaisesDisponibles'),
        ),
        migrations.AddField(
            model_name='productos',
            name='reglasVencimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carProducto_producto', to='banca.CarProducto'),
        ),
        migrations.AddField(
            model_name='mediosdisponibles',
            name='productos',
            field=models.ManyToManyField(to='banca.Productos'),
        ),
        migrations.AddField(
            model_name='logexportadotrans',
            name='transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion_logExportadoTrans', to='banca.Transaccion'),
        ),
        migrations.AddField(
            model_name='comisionestp',
            name='transaccion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='banca.Transaccion'),
        ),
        migrations.AddField(
            model_name='comision',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_comision', to='banca.TipoTransaccion'),
        ),
    ]
