# Generated by Django 2.2.8 on 2020-05-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0002_auto_20200507_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionestp',
            name='suena',
            field=models.CharField(default='Siquesi', max_length=20),
        ),
    ]
