# Generated by Django 2.2.8 on 2020-05-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0003_sonar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comisionestp',
            name='suena',
        ),
    ]
