# Generated by Django 2.2.8 on 2020-05-15 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0004_remove_sonar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisionestp',
            name='transaccion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banca.Transaccion'),
        ),
    ]
