# Generated by Django 2.2.8 on 2020-05-15 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0005_auto_20200515_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='errorRes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_transaccion', to='banca.ErroresTransaccion'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='statusTrans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_transaccion', to='banca.StatusTrans'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipoTrans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_transaccion', to='banca.TipoTransaccion'),
        ),
    ]
