# Generated by Django 2.2.8 on 2020-05-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0006_auto_20200515_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAMI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('monto', models.FloatField()),
                ('unidad', models.CharField(blank=True, max_length=10, null=True)),
                ('pesos', models.FloatField()),
                ('tipo', models.IntegerField(choices=[(0, 'Diaria'), (1, 'Mensual')], default=0)),
            ],
        ),
    ]
