# Generated by Django 2.2.8 on 2020-05-18 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0006_auto_20200515_0605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogExportadoTrans',
        ),
    ]
