# Generated by Django 2.2.8 on 2020-05-16 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0010_auto_20200516_1400'),
        ('banca', '0007_cami'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CAMIM',
        ),
        migrations.AlterField(
            model_name='validacionregulatoria',
            name='idCAMID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validacionR_CAMID', to='banca.CAMI'),
        ),
        migrations.DeleteModel(
            name='CAMID',
        ),
    ]
