# Generated by Django 2.2.8 on 2020-05-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0007_delete_logexportadotrans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediosDisponibles',
        ),
    ]
