# Generated by Django 2.2.8 on 2020-05-18 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0008_auto_20200516_1400'),
        ('banca', '0008_delete_mediosdisponibles'),
    ]

    operations = [
    ]
