# Generated by Django 2.2.8 on 2020-05-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0009_merge_20200518_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediosDisponibles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('productos', models.ManyToManyField(to='banca.Productos')),
            ],
        ),
    ]
