# Generated by Django 2.2.8 on 2020-07-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0013_auto_20200710_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadbnxoutsetsva',
            name='upload',
            field=models.FileField(upload_to='banca/archivos/bnx'),
        ),
        migrations.AlterField(
            model_name='uploadtefout',
            name='upload',
            field=models.FileField(upload_to='banca/archivos/tef'),
        ),
    ]
