# Generated by Django 2.2.8 on 2020-09-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0014_auto_20200714_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotransaccion',
            name='salida',
            field=models.BooleanField(default=True),
        ),
    ]
