# Generated by Django 2.2.8 on 2020-09-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0015_tipotransaccion_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='claveRastreo',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='concepto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
