# Generated by Django 2.2.8 on 2020-09-26 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0015_remove_mediosdisponibles_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transpago_authdet',
            name='transPago_AuthHead',
        ),
        migrations.RemoveField(
            model_name='transpago_authdet',
            name='transaccion',
        ),
        migrations.RemoveField(
            model_name='transpago_authhead',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='transpago_authhead',
            name='user',
        ),
        migrations.DeleteModel(
            name='UploadBNXOutSetSVA',
        ),
        migrations.DeleteModel(
            name='UploadTefOut',
        ),
        migrations.DeleteModel(
            name='TransPago_AuthDet',
        ),
        migrations.DeleteModel(
            name='TransPago_AuthHead',
        ),
    ]
