# Generated by Django 2.2.8 on 2020-09-26 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0016_auto_20200908_1826'),
        ('banca', '0016_auto_20200925_2043'),
    ]

    operations = [
    ]
