# Generated by Django 2.2.8 on 2021-02-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0017_merge_20200925_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_referencia', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Entidades',
            },
        ),
    ]
