# Generated by Django 2.2.8 on 2021-05-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('demograficos', '0042_remove_docextraction_user'),
        ('banca', '0018_entidades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entidades',
            new_name='CodigoConfianza',
        ),
        migrations.AlterModelOptions(
            name='codigoconfianza',
            options={'verbose_name_plural': 'Codigos de confianza'},
        ),
    ]
