# Generated by Django 2.2.8 on 2022-05-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0019_auto_20210512_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorUdis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('valor_monetario', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('udis_cuenta', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Valor Udis',
            },
        ),
    ]
