# Generated by Django 2.2.8 on 2022-06-20 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0021_saldoreservado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saldoreservado',
            options={'verbose_name': 'Saldo reservado', 'verbose_name_plural': 'Saldos reservados'},
        ),
        migrations.AddField(
            model_name='saldoreservado',
            name='tipoTrans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banca.TipoTransaccion', verbose_name='Tipo de transacción'),
        ),
        migrations.AlterField(
            model_name='saldoreservado',
            name='fecha_reservado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
