# Generated by Django 2.2.8 on 2022-07-12 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demograficos', '0047_auto_20220701_1956'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banca', '0022_auto_20220619_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='InguzTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusTrans', models.IntegerField(choices=[(0, 'esperando respuesta'), (1, 'liquidado'), (2, 'devuelto')], default=0)),
                ('rechazada', models.BooleanField(default=False)),
                ('rechazadaMsj', models.CharField(blank=True, max_length=200, null=True)),
                ('fechaOperacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('concepto', models.CharField(blank=True, max_length=128, null=True)),
                ('referencia', models.CharField(max_length=18, null=True)),
                ('causaDevolucion', models.CharField(blank=True, max_length=64, null=True)),
                ('monto', models.CharField(max_length=64, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=64, null=True)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacto_inguz_transaccion', to='demograficos.Contacto')),
                ('ordenante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenante', to=settings.AUTH_USER_MODEL)),
                ('transaccion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banca.Transaccion')),
            ],
            options={
                'verbose_name': 'Transaccion Inguz',
                'verbose_name_plural': 'Transacciones Inguz',
            },
        ),
    ]
