# Generated by Django 3.2 on 2022-12-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0023_inguztransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='inguztransaction',
            name='comprobante_img',
            field=models.ImageField(blank=True, null=True, upload_to='banca/comprobantes'),
        ),
    ]
