# Generated by Django 3.2 on 2022-12-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0023_inguztransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='inguztransaction',
            name='comprobante_img',
            field=models.ImageField(blank=True, null=True, upload_to='banca/comprobantes'),
        ),
        migrations.AddField(
            model_name='inguztransaction',
            name='url_comprobante',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
