# Generated by Django 3.2.15 on 2022-10-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0023_inguztransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotransaccion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('E', 'Enviada'), ('R', 'Recibida'), ('S', 'Especial')], max_length=1, null=True),
        ),
    ]
