# Generated by Django 3.2 on 2022-12-21 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0026_alter_notificacioncobro_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacioncobro',
            name='transaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='banca.inguztransaction'),
        ),
    ]
