# Generated by Django 3.2.16 on 2023-01-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0027_alter_notificacioncobro_transaccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveSmallIntegerField(choices=[(1, 'Nivel 1'), (3, 'Nivel 3')], verbose_name='Nivel de cuenta')),
                ('trans_mes', models.DecimalField(blank=True, decimal_places=2, max_digits=9, max_length=20, null=True, verbose_name='Transferencias al mes')),
                ('saldo_max', models.DecimalField(blank=True, decimal_places=2, max_digits=9, max_length=20, null=True, verbose_name='Saldo máximo')),
                ('dep_efectivo_mes', models.DecimalField(blank=True, decimal_places=2, max_digits=9, max_length=20, null=True, verbose_name='Depósitos en efectivo al mes')),
                ('dep_efectivo_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=9, max_length=20, null=True, verbose_name='Depósitos en efectivo diario')),
                ('ret_efectivo_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=9, max_length=20, null=True, verbose_name='Retiro en efectivo diario')),
            ],
            options={
                'verbose_name_plural': 'Niveles de cuenta',
            },
        ),
    ]
