# Generated by Django 3.2.16 on 2023-01-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0027_alter_notificacioncobro_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotransaccion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('E', 'Enviada'), ('R', 'Recibida'), ('S', 'Especial')], max_length=1, null=True),
        ),
    ]
