# Generated by Django 3.2.16 on 2023-01-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0028_nivelcuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotransaccion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('E', 'Enviada'), ('R', 'Recibida'), ('S', 'Especial')], max_length=1, null=True),
        ),
    ]
