# Generated by Django 3.2.16 on 2023-01-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0029_tipotransaccion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacioncobro',
            name='importe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
