# Generated by Django 3.2.16 on 2023-02-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0030_alter_notificacioncobro_importe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotransaccion',
            name='medio',
            field=models.CharField(blank=True, choices=[('E', 'Enviada'), ('R', 'Recibida'), ('S', 'Especial')], max_length=1, null=True),
        ),
    ]
