# Generated by Django 3.2 on 2023-02-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0031_tipotransaccion_medio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
