# Generated by Django 3.2 on 2023-02-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0032_alter_transaccion_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipotransaccion',
            name='medio',
            field=models.CharField(blank=True, choices=[('E', 'Efectivo'), ('T', 'Transferencia')], max_length=1, null=True),
        ),
    ]
