# Generated by Django 3.2 on 2023-03-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0033_alter_tipotransaccion_medio'),
        ('banca', '0033_comprobante'),
    ]

    operations = [
    ]
