# Generated by Django 3.2 on 2023-03-03 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0033_alter_tipotransaccion_medio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comisionestp',
            name='transaccion',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='comision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banca.comisionestp'),
        ),
    ]
