# Generated by Django 3.2 on 2023-04-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0034_auto_20230303_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionestp',
            name='rangotransacciones',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
