# Generated by Django 3.2 on 2023-05-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0035_auto_20230502_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisionestp',
            name='rangotransacciones',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
