# Generated by Django 3.2 on 2023-06-01 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banca', '0036_alter_comisionestp_rangotransacciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamoZakiTransaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pendiente'), ('L', 'Liquidado'), ('V', 'Vencido')], default='P', max_length=32)),
                ('fechaOperacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('monto', models.CharField(max_length=64, null=True)),
                ('enviada_prestamo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_enviada', to='banca.transaccion')),
                ('recibida_prestamo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_recibida', to='banca.transaccion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_zaki', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PagoZakiTransaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaOperacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('monto', models.CharField(max_length=64, null=True)),
                ('enviada_pago', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_recibida', to='banca.transaccion')),
                ('recibida_pago', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_enviada', to='banca.transaccion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_zaki', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
