# Generated by Django 3.2 on 2023-06-23 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0037_pagozakitransaccion_prestamozakitransaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagozakitransaccion',
            name='prestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='abonos', to='banca.prestamozakitransaccion'),
        ),
        migrations.AlterField(
            model_name='pagozakitransaccion',
            name='enviada_pago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_enviada', to='banca.transaccion'),
        ),
        migrations.AlterField(
            model_name='pagozakitransaccion',
            name='recibida_pago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_recibida', to='banca.transaccion'),
        ),
    ]
