# Generated by Django 2.2.8 on 2020-11-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='Comision_BratD',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='Comision_GPO',
        ),
    ]
