# Generated by Django 2.2.8 on 2020-11-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20201103_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgref',
            name='servicio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='logotypes',
            name='servicio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
