name: PR Django Tests

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main
      - staging
      - test

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt
        pip install -r requirements/dev.txt
    - name: Django Testing
      run: |
        tox
